name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 26
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths

